apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: html-openshift-app
  labels:
    app: html-openshift-app
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: html-openshift-app
  labels:
    app: html-openshift-app
spec:
  source:
    type: Git
    git:
      uri: https://github.com/YannikAckermann/M210
    # Ordner im Repo, wo index.html liegt
    contextDir: Openshift
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: DockerImage
        name: centos/httpd-24-centos7
  output:
    to:
      kind: ImageStreamTag
      name: html-openshift-app:latest
  triggers:
    - type: ConfigChange
    - type: ImageChange
